language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm-nightly

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.x-dev
  - SYMFONY_VERSION=2.8.x-dev

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source

script: bin/phpunit
